.TH qtfm 1 "11 July 2018" "6.1" "QtFM documentation"
.SH NAME
QtFM -\ desktop independent file manager
.SH SYNOPSIS
qtfm [file:///]
.SH DESCRIPTION
Lightweight file manager using Qt.
.SH SEE ALSO
qtfm-tray(1)
.SH BUGS
See https://github.com/rodlie/qtfm/issues
.SH AUTHOR
Ole-Andre Rodlie (ole.andre.rodlie@gmail.com)
