.TH qtfm-tray 1 "01 August 2018" "6.1" "QtFM documentation"
.SH NAME
QtFM -\ desktop independent file manager
.SH SYNOPSIS
qtfm-tray
.SH DESCRIPTION
System tray daemon for QtFM.
.SH FILES
.I ~/.config/qtfm6/qtfm6.conf
.RS
Per user configuration file.
.RE
.SH SEE ALSO
qtfm(1)
.SH BUGS
See https://github.com/rodlie/qtfm/issues
.SH AUTHOR
Ole-Andre Rodlie (ole.andre.rodlie@gmail.com)
