.TH qtfm-tray 8 "11 July 2018" "6.1" "QtFM documentation"
.SH NAME
QtFM -\ desktop independent file manager
.SH SYNOPSIS
qtfm-tray
.SH DESCRIPTION
System tray daemon for QtFM.
.SH SEE ALSO
qtfm(8)
.SH BUGS
See https://github.com/rodlie/qtfm/issues
.SH AUTHOR
Ole-Andre Rodlie (ole.andre.rodlie@gmail.com)
